name: Deploy Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Extract Docker metadata
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: ghcr.io/yojigenserver/doublecommander
              tags: |
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=semver,pattern={{major}}

          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./Dockerfile
              platforms: linux/amd64,linux/arm64
              push: ${{ github.event_name != 'pull_request' }}
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
